version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building the project..."
      - npm run build
  post_build:
    commands:
      - echo "Build completed successfully."
      - ls -la dist-server

artifacts:
  files:
    - dist-server/**/*
    - package.json
    - package-lock.json
    - server/**/*
    - buildspec-test.yml
